services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=upload
    volumes:
      - "./docker:/docker-entrypoint-init-db.d"