services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pg_user
      - POSTGRES_PASSWORD=pg_password
      - POSTGRES_DB=upload
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"